### Pre request script
GET http://localhost:8761/eureka/v2/apps
Accept: application/json

> {%
    const jsonArray = response.body['applications']
    let applications = jsonArray.application;
    for (let i = 0; i < applications.length; i++) {
        let inst = applications[i];
        let name = inst.name;
        if (name === 'APP-HTML-PARSER-SERVICE') {
            let host = inst.instance[0].hostName
            let port = inst.instance[0].port.$;
            client.log("Service name: " + name)
            client.log("host: " + host)
            client.global.set("app-http-parser-service-host", host)
            client.log("port: " + port)
            client.global.set("app-http-parser-service-port", port)
        }
    }
%}

###
POST http://localhost:{{app-http-parser-service-port}}/v1/bills
Content-Type: application/json

{
  "link": "https://itd.rada.gov.ua/billInfo/Bills/Card/42664",
  "number": "9672",
  "name": "Проект Закону про внесення змін до статті 23 Закону України \"Про мобілізаційну підготовку та мобілізацію\"",
  "registrationDate": "2023-09-04"
}