server:
  port: ${APP_USER_SUBSCRIPTION_SERVICE_SERVER_PORT:8080}

spring:
  application:
    name: app-ui-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
