server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://${APP_STORAGE_POSTGRESQL_HOSTNAME}/${APP_STORAGE_POSTGRESQL_DBNAME}?user=${APP_STORAGE_POSTGRESQL_USER}&password=${APP_STORAGE_CLOUD_KAFKA_PASSWORD}