server:
  port: ${APP_STORAGE_SERVICE_PORT:8087}

spring:
  datasource:
    url: jdbc:postgresql://${APP_STORAGE_SERVICE_POSTGRESQL_HOSTNAME}/${APP_STORAGE_SERVICE_POSTGRESQL_DBNAME}?user=${APP_STORAGE_SERVICE_POSTGRESQL_USER}&password=${APP_STORAGE_SERVICE_POSTGRESQL_PASSWORD}