server:
  port: ${APP_SCHEDULER_SERVICE_PORT:8086}

scheduled:
  task:
    job:
      cron: ${APP_SCHEDULER_SERVICE_CRONE:0/10 * * * * *}

html-service:
  base-url: ${APP_HTML_SERVICE_BASE_URL:http://localhost:8085}
  endpoint:
    bills: ${APP_HTML_SERVICE_FIND_BILLS_ENDPOINT:/v1/bills}
    searchResults: ${APP_HTML_SERVICE_SEARCH_ENDPOINT:/v1/searchResults}

diff-service:
  base-url: ${APP_DIFF_SERVICE_BASE_URL:http://localhost:8088}
  endpoint: ${APP_DIFF_SERVICE_ENDPOINT:/v1/diff}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:false}