server:
  port: ${APP_SCHEDULER_SERVICE_PORT:0}

spring:
  application:
    name: app-scheduler-service

scheduled:
  task:
    job:
      cron: ${APP_SCHEDULER_SERVICE_CRONE:0/30 * * * * *}

html-service:
  application:
    name: ${APP_HTML_SERVICE_APPLICATION_NAME:app-html-parser-service}
  endpoint:
    bills: ${APP_HTML_SERVICE_FIND_BILLS_ENDPOINT:/v1/bills}
    searchResults: ${APP_HTML_SERVICE_SEARCH_ENDPOINT:/v1/searchResults}

diff-service:
  application:
    name: ${APP_DIFF_SERVICE_APPLICATION_NAME:app-diff-service}
  endpoint: ${APP_DIFF_SERVICE_ENDPOINT:/v1/diff}

user-subscription-service:
  application:
    name: ${APP_USER_SUBSCRIPTION_SERVICE_APPLICATION_NAME:app-user-subscription-service}
  endpoint:
    subscriptions:
      active: ${APP_USER_SUBSCRIPTION_SERVICE_ENDPOINT:/v1/subscriptions/active}

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}