server:
  port: ${APP_USER_SERVICE_PORT:0}

spring:
  application:
    name: app-user-service

  r2dbc:
    url: r2dbc:postgresql://${APP_USER_POSTGRESQL_HOSTNAME}/${APP_USER_SERVICE_POSTGRESQL_DBNAME}
    username: ${APP_USER_SERVICE_POSTGRESQL_USER}
    password: ${APP_USER_SERVICE_POSTGRESQL_PASSWORD}

  liquibase:
    user: ${APP_USER_SERVICE_POSTGRESQL_USER}
    url: jdbc:postgresql://${APP_USER_POSTGRESQL_HOSTNAME}/${APP_USER_SERVICE_POSTGRESQL_DBNAME}
    password: ${APP_USER_SERVICE_POSTGRESQL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}