server:
  port: ${APP_HTML_SERVICE_PORT:0}

spring:
  application:
    name: app-html-parser-service

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

proxy-service:
  application:
    name: app-proxy-service
  endpoint:
    proxy:
      bills: /v1/bills
      statuses: /v1/bill/statuses

management:
  health.circuitbreakers.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}

springdoc:
  swagger-ui:
    path: /