server:
  port: ${APP_DIFF_SERVICE_PORT:0}

spring:
  application:
    name: app-diff-service

bill-storage-service:
  application:
    name: ${APP_BILL_STORAGE_SERVICE_APPLICATION_NAME:app-storage-service}
  endpoint:
    bills: ${APP_BILL_STORAGE_SERVICE_BILL_ENDPOINT:/bills}
    bill-statuses: ${APP_BILL_STORAGE_SERVICE_BILL_STATUSES_ENDPOINT:/billStatuses}

mail-service:
  application:
    name: ${APP_MAIL_SERVICE_APPLICATION_NAME:app-mail-service}
  endpoint:
    send-email: /v1/emails
  template:
    title: "The status of %s bill has changed"
    message: "Bill number: %s\nName: %s\nNew status: %s"

  test:
    default-recipient: ${APP_MAIL_SERVICE_DEFAULT_RECIPIENT:test_test@gmail.com}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true