server:
  port: ${APP_DIFF_SERVICE_PORT:8088}

storage-service:
  base-url: ${APP_STORAGE_SERVICE_BASE_URL:http://localhost:8087}
  endpoint:
    bills: ${APP_STORAGE_SERVICE_BILL_ENDPOINT:/bills}

mail-service:
  base-url: ${APP_MAIL_SERVICE_URL:http://localhost:8089}
  endpoint:
    send-email: /mail/send
  template:
    title: "The status of %s bill has changed"
    message: "Bill number: %s\nName: %s\nNew status: %s"

  test:
    default-recipient: ${APP_MAIL_SERVICE_DEFAULT_RECIPIENT:test_test@gmail.com}