server:
  port: ${APP_DIFF_SERVICE_PORT:8088}

bill-storage-service:
  base-url: ${APP_BILL_STORAGE_SERVICE_BASE_URL:http://localhost:8087}
  endpoint:
    bills: ${APP_BILL_STORAGE_SERVICE_BILL_ENDPOINT:/bills}
    bill-statuses: ${APP_BILL_STORAGE_SERVICE_BILL_STATUSES_ENDPOINT:/billStatuses}

mail-service:
  base-url: ${APP_MAIL_SERVICE_URL:http://localhost:8089}
  endpoint:
    send-email: /v1/emails
  template:
    title: "The status of %s bill has changed"
    message: "Bill number: %s\nName: %s\nNew status: %s"

  test:
    default-recipient: ${APP_MAIL_SERVICE_DEFAULT_RECIPIENT:test_test@gmail.com}