server:
  port: ${APP_DIFF_SERVICE_PORT:8088}

storage-service:
  url: ${APP_STORAGE_SERVICE_URL:http://localhost:8087}
  path:
    find-bills: ${APP_STORAGE_SERVICE_FIND_BILLS_PATH:/bills}

mail-service:
  url: ${APP_MAIL_SERVICE_URL:http://localhost:8089}
  path:
    send-email: /mail/send