server:
  port: ${APP_GATEWAY_SERVICE_PORT:8765}

spring:
  application:
    name: app-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: app-user-subscription-service
          uri: lb://app-user-subscription-service
          predicates:
            - Path=/v1/subscriptions, /v1/subscriptions/subscribe, /v1/subscriptions/unsubscribe
            - Method=GET, POST

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/