server:
  port: ${APP_GATEWAY_SERVICE_PORT:8765}

spring:
  application:
    name: app-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: app-user-subscription-service
          uri: lb://app-user-subscription-service
          predicates:
            - Path=/v1/subscriptions, /v1/subscriptions/subscribe, /v1/subscriptions/unsubscribe
            - Method=GET, POST
        - id: app-html-parser-service
          uri: lb://app-html-parser-service
          predicates:
            - Path=/v1/bills/{number}
            - Method=GET
        - id: app-user-service
          uri: lb://app-user-service
          predicates:
            - Path=/v1/users/{username}, /v1/users
            - Method=GET, POST

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/