server:
  port: ${APP_BILL_STORAGE_SERVICE_PORT:0}

spring:
  application:
    name: app-storage-service

  datasource:
    url: jdbc:postgresql://${APP_BILL_STORAGE_SERVICE_POSTGRESQL_HOSTNAME}/${APP_BILL_STORAGE_SERVICE_POSTGRESQL_DBNAME}
    username: ${APP_BILL_STORAGE_SERVICE_POSTGRESQL_USER}
    password: ${APP_BILL_STORAGE_SERVICE_POSTGRESQL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}