server:
  port: ${APP_DISCOVERY_SERVICE_PORT:8761}

spring:
  application:
    name: ${APP_DISCOVERY_SERVICE_APP_NAME:app-discovery-service}

eureka:
  instance:
    hostname: ${APP_DISCOVERY_SERVICE_INSTANCE_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/