server:
  port: ${APP_USER_SUBSCRIPTION_SERVICE_SERVER_PORT:0}

spring:
  application:
    name: app-user-subscription-service

  data:
    mongodb:
      uri: ${APP_USER_SUBSCRIPTION_SERVICE_MONGODB_URI:uri}
      database: ${APP_USER_SUBSCRIPTION_SERVICE_MONGODB_DATABASE:user-subscription-db}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:true}